parameters:
#    axstrad_article.example.class: Axstrad\Bundle\ContentBundle\Example

services:
#    axstrad_article.example:
#        class: %axstrad_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
