parameters:
    axstrad_content.twig.extension.class: Axstrad\Bundle\ContentBundle\Twig\Extension

services:
    axtsrad_content.twig.extension:
        class: %axstrad_content.twig.extension.class%
        tags:
            - { name: twig.extension }

